### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by varya** [Ceesaxp/as-convert-russian#11]
Could you please write in the README how to install this script? Thanks.

**Comment by Ceesaxp** [comment]
Sure, but it is available here: https://github.com/Ceesaxp/as-convert-russian/wiki/Installing%20Convert%20Russian

**Comment by monolithed** [comment]
There's no such directory in Sierra

**Comment by monolithed** [comment]
An instruction:

```
mkdir -p ~/Library/iTunes/Scripts
git clone --depth=1 git@github.com:Ceesaxp/as-convert-russian.git
rm -rf as-convert-russian/{.git,Convert\ Cyrillic.scpt}
```

**Comment by Ceesaxp** [comment]
Better late than never — instructions are updated now ))

**Comment by estaf1001** [comment]
> An instruction:
> 
> ```
> mkdir -p ~/Library/iTunes/Scripts
> git clone --depth=1 git@github.com:Ceesaxp/as-convert-russian.git
> rm -rf as-convert-russian/{.git,Convert\ Cyrillic.scpt}
> ```

And what to do next?
I're turning script menu on. I watch that scripts in ~/Library/Scripts/Applications/Music/ - ok. But in script menu I don't view any dialogs.
