### ISSUE TITLE
Convert Cyrillic.scpt needs to be recompiled

### ISSUE THREAD

**Issue by ikatkov** [Ceesaxp/as-convert-russian#12]
Convert Cyrillic.scpt needs to be recompiled it does not have 
https://github.com/Ceesaxp/as-convert-russian/issues/9

**Comment by ikatkov** [comment]
see https://github.com/Ceesaxp/as-convert-russian/pull/13

**Comment by ikatkov** [comment]
ping?

**Comment by Ceesaxp** [comment]
Done
