### ISSUE TITLE
Й instead of И in uppercase

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Ceesaxp/as-convert-russian#9]
```
I got ЗЕМФЙРА instead of ЗЕМФИРА as conversion result...
```

Original issue reported on code.google.com by `lito...@gmail.com` on 25 Dec 2011 at 12:22

Attachments:
* [Screen Shot 2011-12-25 at 2.21.35.png](https://storage.googleapis.com/google-code-attachments/as-convert-russian/issue-9/comment-0/Screen Shot 2011-12-25 at 2.21.35.png)

**Comment by pvoznenko** [comment]
This bug is fixed with commit f4f254f . @Ceesaxp please verify

**Comment by Ceesaxp** [comment]
Confirmed
